### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by mlanius** [xing/XNGAPIClient#26]
After receiving my production key and getting a new callback URL (format: http://www.myDomain.de) my question is: how to handle this second callback URL?
The first callback URL I put in my App custom target properties as described in the readme.md file (format: xingapp+customer key). Do I have to use both URLs (If yes, which is the correct syntax?) or to substitute the first one with the other? At the moment I try both URLs together but this doesn't work.

Thanks, Martin

**Comment by pietbrauer** [comment]
Closing as timed out.
