### ISSUE TITLE
Experiencing a problem with XNGAPIClient.logout()

### ISSUE THREAD

**Issue by vanNiewoehner** [xing/XNGAPIClient#68]
Hello together,
I've the issue that whenever the user logs out of the iOS App, it is not possible to log in with another user. In case of a log out, I do call the provided logout() methods but whenever I click on "Log in with XING", instead of being presented to the web view with e-mail and password field, the web view disappears just a second after it was presented and the previous user is automatically logged in. Is this a know issue and do you guys know a workaround for that?

Best regards
Sebastian

**Comment by pietbrauer** [comment]
Hey Sebastian,

thats a rather interesting issue and not known until now. May it be that the web view still has the token and therefore the user is still logged in? If so you would need to flush the cookies from the UIWebView somehow. Could you try that out?

Cheers,

Piet.

**Comment by vanNiewoehner** [comment]
Wow, thanks for the fast reply. I'll give that a try and get back to you as soon as I know more ;)

**Comment by pietbrauer** [comment]
Cool. Another thing I would try is open Safari, go to `xing.com` and see if the user is still logged in. (Sorry for closing the issue, I hit the wrong button).

**Comment by vanNiewoehner** [comment]
Your first tip led me to the right solution, deleting the sessions of UIWebView does prevent the WebView from closing immediately and the XING login page is presented to the user! Do you also know which specific session is created by XING to store the login information? I guess deleting all session by default would be bad practice ;)

**Comment by pietbrauer** [comment]
Not sure right now. But I think @m0rk is digging into some related issue in our main app. @m0rk could you share your experience :fire_engine:
