### ISSUE TITLE
XNGAPIClient is missing UIKit Import

### ISSUE THREAD

**Issue by pixelkind** [xing/XNGAPIClient#79]
If I use the XNGAPIClient in Swift Xcode reports 3 expected type errors. If you look at the error message the UIImage class could not be found. You can fix it using the

#import <UIKit/UIKit.h> 

in the XNGAPIClient.h or in the categories where UIImage is used.

**Comment by Ruenzuo** [comment]
Thanks a lot for the heads up :blush: ! We are working on supporting Swift projects. You could use the `swift_support` branch until this PR is merged: https://github.com/xing/XNGAPIClient/pull/80
